#!/usr/bin/env python3
"""Serve the Aokigahara free-roam viewer locally.

The original handover shipped a launch_viewer.py that was lost in the truncated
archive tail; this is a functional replacement. The viewer must be served over
HTTP (ES modules, binary terrain grids and ../models/ references do not load
from file://). The server root is the repository root so that
viewer/ can reach ../models/Aokigahara_Surface_Terrain.glb.

Usage:  python3 launch_viewer.py [--port 8000] [--open]
Then open the printed address (default http://127.0.0.1:8000/viewer/).
"""
import argparse, http.server, json, mimetypes, os, socketserver, sys, webbrowser
from functools import partial

ROOT = os.path.dirname(os.path.abspath(__file__))
mimetypes.add_type('text/javascript', '.js')
mimetypes.add_type('text/javascript', '.mjs')
mimetypes.add_type('model/gltf-binary', '.glb')
mimetypes.add_type('model/gltf+json', '.gltf')
mimetypes.add_type('application/octet-stream', '.f32')
mimetypes.add_type('application/octet-stream', '.u8')
mimetypes.add_type('application/json', '.json')

DERIVED = {
    'Aokigahara_Cave_Corridor.glb': 'construction_code/export_scene.py',
    'Aokigahara_Instanced_Forest.glb': 'construction_code/export_forest.py',
    'Aokigahara_World.glb': 'construction_code/assemble_world.py',
    'Aokigahara_Surface_Terrain.glb': 'construction_code/export_scene.py',
    'Aokigahara_Regional_Terrain.glb': 'construction_code/export_scene.py',
}

def refresh_export_index():
    """Record which derived GLB exports this checkout actually contains.

    The viewer reads assets/derived-exports.json so it can grey out downloads that are not here
    instead of offering links that 404. The exports are rebuildable products, so which ones exist
    is a property of the checkout, not of the project. Rewritten only when it changes, so a clean
    tree stays clean.
    """
    models = os.path.join(ROOT, 'models')
    present = sorted(f for f in DERIVED if os.path.exists(os.path.join(models, f)))
    index = {
        'note': 'Derived GLB exports present in this checkout. Regenerated by launch_viewer.py.',
        'present': present,
        'missing': {f: s for f, s in sorted(DERIVED.items()) if f not in present},
    }
    out = os.path.join(ROOT, 'viewer', 'assets', 'derived-exports.json')
    body = json.dumps(index, indent=2) + '\n'
    try:
        if os.path.exists(out) and open(out, encoding='utf-8').read() == body:
            return index
        with open(out, 'w', encoding='utf-8') as fh:
            fh.write(body)
    except OSError as exc:
        print(f'could not refresh {out}: {exc}')
    return index


class Handler(http.server.SimpleHTTPRequestHandler):
    def end_headers(self):
        self.send_header('Cache-Control', 'no-cache')
        super().end_headers()
    def log_message(self, fmt, *args):
        if '--quiet' not in sys.argv:
            super().log_message(fmt, *args)

def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--port', type=int, default=8000)
    ap.add_argument('--bind', default='127.0.0.1')
    ap.add_argument('--open', action='store_true', help='open the viewer in the default browser')
    ap.add_argument('--quiet', action='store_true')
    a = ap.parse_args()
    index = refresh_export_index()
    if index['missing']:
        print('derived exports not in this checkout: ' + ', '.join(index['missing']))
    url = f'http://{a.bind}:{a.port}/viewer/'
    socketserver.TCPServer.allow_reuse_address = True
    with socketserver.ThreadingTCPServer((a.bind, a.port), partial(Handler, directory=ROOT)) as srv:
        print(f'Aokigahara viewer: {url}   (serving {ROOT}; Ctrl+C to stop)')
        if a.open:
            webbrowser.open(url)
        try:
            srv.serve_forever()
        except KeyboardInterrupt:
            print('\nstopped')

if __name__ == '__main__':
    main()
