// Aokigahara free-roam viewer — production pass 2 (near-field ground system, tree library v2, stand structure, lighting presets).
// Coordinate frame unchanged: origin 138.658 E 35.4775 N (WGS84), x east, z south, y = elevation - 900 m. 1 unit = 1 m.
import {computeBoundsTree,acceleratedRaycast} from './vendor/mesh-bvh.module.js';
import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {GLTFExporter} from 'three/addons/exporters/GLTFExporter.js';
import {Sky} from 'three/addons/objects/Sky.js';
THREE.BufferGeometry.prototype.computeBoundsTree=computeBoundsTree;THREE.Mesh.prototype.raycast=acceleratedRaycast;
const $=id=>document.getElementById(id), canvas=$('world'), scene=new THREE.Scene();
canvas.tabIndex=0;
const camera=new THREE.PerspectiveCamera(62,innerWidth/innerHeight,.1,80000);camera.rotation.order='YXZ';
let renderer;try{renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});}catch(e){$('load-message').textContent='This viewer requires WebGL 2. You can still download the GLB model files using the controls.';$('menu-button').onclick=()=>{$('loading').style.display='none';$('panel').hidden=false;};throw e;}
renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.95;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
// ---------------------------------------------------------------- lighting (three plausible daylight states; none is a dated weather record)
const ambient=new THREE.HemisphereLight(0xb9c6cc,0x2c3323,1.1);scene.add(ambient);
const sun=new THREE.DirectionalLight(0xfff1dc,2.0);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-68,right:68,top:68,bottom:-68,near:1,far:260});sun.shadow.bias=-.0002;sun.shadow.normalBias=.06;sun.shadow.radius=3;scene.add(sun,sun.target);
const sky=new Sky();sky.scale.setScalar(450000);scene.add(sky);const u=sky.material.uniforms;
scene.fog=new THREE.FogExp2(0x8e978c,.0035);const sunVector=new THREE.Vector3();
const PRESETS={overcast:{label:'Overcast (neutral reference)',sun:.55,hemi:1.9,hemiSky:0xc9d2d4,hemiGround:0x2d3426,turb:20,ray:.25,mie:.08,fog:0x9aa399,exposure:.9},
 soft:{label:'Soft sun through canopy',sun:2.0,hemi:1.35,hemiSky:0xb9c6cc,hemiGround:0x2c3323,turb:6,ray:1.2,mie:.006,fog:0x8e978c,exposure:.95},
 clear:{label:'Clear midday',sun:3.3,hemi:.9,hemiSky:0xaec6d8,hemiGround:0x2a3122,turb:2.8,ray:1.4,mie:.0035,fog:0x93a09a,exposure:1.0}};
let preset='soft';
function setSun(){const angle=+$('sun').value;const p=PRESETS[preset];sunVector.setFromSphericalCoords(1,THREE.MathUtils.degToRad(90-angle),THREE.MathUtils.degToRad(155));u.sunPosition.value.copy(sunVector);u.turbidity.value=p.turb;u.rayleigh.value=p.ray;u.mieCoefficient.value=p.mie;u.mieDirectionalG.value=.82;
 sun.intensity=p.sun*(.75+.25*Math.min(1,angle/40));sun.color.setHSL(.09,.28,.9);ambient.intensity=p.hemi;ambient.color.set(p.hemiSky);ambient.groundColor.set(p.hemiGround);scene.fog.color.set(p.fog);renderer.toneMappingExposure=p.exposure;}
// ---------------------------------------------------------------- state
const grids={},contexts={},loader=new GLTFLoader(),texloader=new THREE.TextureLoader();
let forestData,forestMeta,forestAug,treeGrid=new Map(),lib={},fernProto=[],logGeo=null,logMat=null,trees=[],small=[],ready=false,mode='walk',yaw=.45,pitch=-.025,lookDragging=false,previousPointer,quality='balanced',lastForest=new THREE.Vector3(Infinity,0,Infinity),lastShadow=new THREE.Vector3(Infinity,0,Infinity),entered=false;
const forestGroup=new THREE.Group(),decorGroup=new THREE.Group(),pathGroup=new THREE.Group(),groundGroup=new THREE.Group();forestGroup.name='Procedural forest constrained by mapped communities';decorGroup.name='Representative ground detail';groundGroup.name='Near-field procedural lava/moss ground (evidence-constrained, not surveyed microrelief)';scene.add(forestGroup,decorGroup,pathGroup,groundGroup);
let surfaceModel=null,matureTemplate=null,heroTrees=[];
async function json(url){const r=await fetch(url);if(!r.ok)throw new Error(`${url}: HTTP ${r.status}`);return r.json();}
async function glb(url){return (await loader.loadAsync(url)).scene;}
function status(s,n){$('load-message').textContent=s;$('progress').value=n;}
function toast(s,d=5500){$('toast').textContent=s;$('toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').style.display='none',d);}
async function getGrid(n){const m=await json(`assets/terrain/${n}-height.json`);const [raw,cl]=await Promise.all([fetch(`assets/terrain/${m.file}`).then(r=>r.arrayBuffer()),fetch(`assets/terrain/${n}-landcover.u8`).then(r=>r.arrayBuffer())]);grids[n]={m,h:new Float32Array(raw),cl:new Uint8Array(cl)};}
function sample(x,z){for(const n of ['local','study','regional']){const g=grids[n],m=g.m;if(x<m.minX||x>m.maxX||z<m.minZ||z>m.maxZ)continue;const u=(x-m.minX)/m.dx,v=(z-m.minZ)/m.dz,i=Math.min(m.width-2,Math.floor(u)),j=Math.min(m.height-2,Math.floor(v)),a=u-i,b=v-j,q=j*m.width+i;return (g.h[q]*(1-a)+g.h[q+1]*a)*(1-b)+(g.h[q+m.width]*(1-a)+g.h[q+m.width+1]*a)*b-900;}return null;}
function landclass(x,z){for(const n of ['local','study','regional']){const g=grids[n],m=g.m;if(x<m.minX||x>m.maxX||z<m.minZ||z>m.maxZ)continue;const i=Math.max(0,Math.min(m.width-1,Math.round((x-m.minX)/m.dx))),j=Math.max(0,Math.min(m.height-1,Math.round((z-m.minZ)/m.dz)));return g.cl[j*m.width+i]||0;}return 0;}
// deterministic hashing / value noise (shared by ground relief, placement and audit reproducibility)
function rand(i,j,k=0){let n=(Math.imul(i,374761393)^Math.imul(j,668265263)^Math.imul(k,144269))>>>0;n=Math.imul(n^(n>>>13),1274126177)>>>0;return ((n^(n>>>16))>>>0)/4294967296;}
function vn(x,z,k){const i=Math.floor(x),j=Math.floor(z),fx=x-i,fz=z-j,sx=fx*fx*(3-2*fx),sz=fz*fz*(3-2*fz);const a=rand(i,j,k),b=rand(i+1,j,k),c=rand(i,j+1,k),d=rand(i+1,j+1,k);return (a*(1-sx)+b*sx)*(1-sz)+(c*(1-sx)+d*sx)*sz;}
function fbm(x,z,k,o=4){let s=0,a=1,n=0;for(let q=0;q<o;q++){s+=a*vn(x,z,k+q*7);n+=a;x=x*2.03+1.7;z=z*1.97+.3;a*=.5;}return s/n;}
const smooth=(a,b,x)=>{const t=Math.min(1,Math.max(0,(x-a)/(b-a)));return t*t*(3-2*t);};
// ---------------------------------------------------------------- paths (OSM centre lines; widths approximated, edges irregular)
const segments=[],segmentGrid=new Map();function initSegments(ctx){for(const p of ctx.paths){if(p.access==='private'||p.access==='no')continue;for(let k=1;k<p.coordinates.length;k++){const a=p.coordinates[k-1],b=p.coordinates[k],s=[a[0],a[1],b[0],b[1],p.kind==='road'?3.4:.85];segments.push(s);for(let j=Math.floor((Math.min(a[1],b[1])-8)/128);j<=Math.floor((Math.max(a[1],b[1])+8)/128);j++)for(let i=Math.floor((Math.min(a[0],b[0])-8)/128);i<=Math.floor((Math.max(a[0],b[0])+8)/128);i++){const key=i+','+j;if(!segmentGrid.has(key))segmentGrid.set(key,[]);segmentGrid.get(key).push(s);}}}}
function pathInfo(x,z){let best=Infinity,hw=.85;for(const s of segmentGrid.get(Math.floor(x/128)+','+Math.floor(z/128))??[]){if(x<Math.min(s[0],s[2])-8||x>Math.max(s[0],s[2])+8||z<Math.min(s[1],s[3])-8||z>Math.max(s[1],s[3])+8)continue;const dx=s[2]-s[0],dz=s[3]-s[1],t=THREE.MathUtils.clamp(((x-s[0])*dx+(z-s[1])*dz)/(dx*dx+dz*dz||1),0,1),d=Math.hypot(x-s[0]-t*dx,z-s[1]-t*dz);if(d<best){best=d;hw=s[4];}}return [best,hw];}
function pathWeight(x,z){const [d,hw]=pathInfo(x,z);if(d>hw+3)return 0;const w=hw*(.75+.5*vn(x/2.6,z/2.6,71));return 1-smooth(w,w+.9+.6*vn(x/1.1,z/1.1,72),d);}
function onPath(x,z){return pathWeight(x,z)>.35;}
// ---------------------------------------------------------------- near-field relief: PROCEDURAL lava micro-morphology (lobes, blocks, clefts) + root mounds. DEM carries the macro terrain.
const PATCH_SIZE=120,PATCH_N=200,PATCH_HALF=PATCH_SIZE/2;let patchCX=Infinity,patchCZ=Infinity,groundPatch=null;
function reliefRaw(x,z){const lobes=(fbm(x/9,z/9,900)-.5)*1.15,blocks=(fbm(x/2.3,z/2.3,910,3)-.5)*.8+(vn(x/1.1,z/1.1,915)-.5)*.22,micro=(vn(x/.75,z/.75,920)-.5)*.14,r=Math.max(0,1-Math.abs(fbm(x/16,z/16,930,2)-.5)*14);return lobes+blocks+micro-.42*r*r;}
function nearTrees(x,z,r){const out=[];const c=Math.ceil(r/10);const ii=Math.floor(x/10),jj=Math.floor(z/10);for(let j=jj-c;j<=jj+c;j++)for(let i=ii-c;i<=ii+c;i++){const cell=treeGrid.get(i+','+j);if(cell)for(const q of cell){const dx=forestData[q]-x,dz=forestData[q+2]-z;if(dx*dx+dz*dz<r*r)out.push(q);}}return out;}
function mound(x,z){let m=0;for(const q of nearTrees(x,z,4.2)){const dx=forestData[q]-x,dz=forestData[q+2]-z,s=forestAug[q/6*4],d2=dx*dx+dz*dz;m+=.24*s*Math.exp(-d2/(2*1.35*1.35*s));}return Math.min(m,.5);}
function groundLift(x,z,cx=patchCX,cz=patchCZ){const r=Math.max(Math.abs(x-cx),Math.abs(z-cz));const fade=1-smooth(PATCH_HALF-14,PATCH_HALF-1.5,r);if(fade<=0)return .02;const pw=pathWeight(x,z);let h=.58+reliefRaw(x,z)*(1-pw*.85)+mound(x,z)*(1-pw);return .02+(h-.02)*fade;}
function groundY(x,z){const s=sample(x,z);return s===null?null:s+groundLift(x,z);}
function buildGroundPatch(cx,cz){patchCX=cx;patchCZ=cz;const n=PATCH_N,step=PATCH_SIZE/n,N1=n+1,h=new Float32Array(N1*N1),pw=new Float32Array(N1*N1);
 for(let j=0;j<N1;j++)for(let i=0;i<N1;i++){const x=cx-PATCH_HALF+i*step,z=cz-PATCH_HALF+j*step;h[j*N1+i]=(sample(x,z)??0)+groundLift(x,z,cx,cz);pw[j*N1+i]=pathWeight(x,z);}
 const pos=new Float32Array(N1*N1*3),uv=new Float32Array(N1*N1*2),w=new Float32Array(N1*N1*4),idx=new Uint32Array(n*n*6);
 for(let j=0;j<N1;j++)for(let i=0;i<N1;i++){const k=j*N1+i,x=cx-PATCH_HALF+i*step,z=cz-PATCH_HALF+j*step;pos[k*3]=x;pos[k*3+1]=h[k];pos[k*3+2]=z;uv[k*2]=x;uv[k*2+1]=z;
  const hl=h[j*N1+Math.max(0,i-1)],hr=h[j*N1+Math.min(n,i+1)],hd=h[Math.max(0,j-1)*N1+i],hu=h[Math.min(n,j+1)*N1+i];const slope=Math.hypot((hr-hl)/(2*step),(hu-hd)/(2*step)),curv=(hl+hr+hd+hu-4*h[k])/(step*step);
  const rockN=fbm(x/5.5,z/5.5,940,3),litN=fbm(x/11,z/11,950,3),cl=landclass(x,z);
  let rock=Math.min(1,.95*smooth(.30,.75,slope)+.6*smooth(-.12,-.45,curv)+.55*smooth(.62,.8,rockN)),litter=Math.min(1,smooth(.5,.7,litN)*(cl===2?1.2:.95)+.45*smooth(.10,.35,curv)+.5*smooth(.05,.35,pw[k])*(1-smooth(.5,.9,pw[k]))),path=pw[k];
  const m=mound(x,z);rock*=1-.7*Math.min(1,m*2.5);litter*=1-.3*Math.min(1,m*2.5);
  let moss=Math.max(0,1-.85*rock-.8*litter)*(1-path);rock*=1-path;litter*=1-path;const sum=moss+rock+litter+path+1e-6;w[k*4]=moss/sum;w[k*4+1]=rock/sum;w[k*4+2]=litter/sum;w[k*4+3]=path/sum;}
 let q=0;for(let j=0;j<n;j++)for(let i=0;i<n;i++){const a=j*N1+i;idx[q++]=a;idx[q++]=a+N1;idx[q++]=a+1;idx[q++]=a+1;idx[q++]=a+N1;idx[q++]=a+N1+1;}
 const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(pos,3));g.setAttribute('uv',new THREE.BufferAttribute(uv,2));g.setAttribute('aWeights',new THREE.BufferAttribute(w,4));g.setIndex(new THREE.BufferAttribute(idx,1));g.computeVertexNormals();g.computeBoundingSphere();
 if(groundPatch){groundGroup.remove(groundPatch);groundPatch.geometry.dispose();}groundPatch=new THREE.Mesh(g,groundMats.ground);groundPatch.name='Near-field ground: DEM + procedural Jogan lava relief + root mounds; moss/rock/litter/path weights';groundPatch.receiveShadow=true;groundPatch.castShadow=false;groundGroup.add(groundPatch);}
// ---------------------------------------------------------------- base terrain layer weights
// The near-field patch writes per-vertex moss/rock/litter/trail proportions into aWeights.
// The corridor terrain inside the Surface GLB shares that same layered material but ships no such
// attribute, so the shader read the WebGL default for an unbound attribute — (0,0,0,1) — which is
// pure trail. The guard that was meant to catch this tests the sum against 0.01, and (0,0,0,1)
// sums to exactly 1, so it never fired: every square metre beyond the 120 m patch shaded as
// compacted trail cinder. Evaluate the same weight model here, driven by the same procedural lava
// relief, so the ground reads continuously across the patch boundary instead of changing material.
function buildBaseWeights(mesh){
 const g=mesh.geometry,pos=g.attributes.position,n=pos.count,w=new Float32Array(n*4);
 const step=PATCH_SIZE/PATCH_N,v=new THREE.Vector3();
 const H=(x,z)=>(sample(x,z)??0)+reliefRaw(x,z);
 for(let i=0;i<n;i++){
  v.fromBufferAttribute(pos,i).applyMatrix4(mesh.matrixWorld);const x=v.x,z=v.z;
  const h0=H(x,z),hl=H(x-step,z),hr=H(x+step,z),hd=H(x,z-step),hu=H(x,z+step);
  const slope=Math.hypot((hr-hl)/(2*step),(hu-hd)/(2*step)),curv=(hl+hr+hd+hu-4*h0)/(step*step);
  const pw=pathWeight(x,z),rockN=fbm(x/5.5,z/5.5,940,3),litN=fbm(x/11,z/11,950,3),cl=landclass(x,z);
  let rock=Math.min(1,.95*smooth(.30,.75,slope)+.6*smooth(-.12,-.45,curv)+.55*smooth(.62,.8,rockN));
  let litter=Math.min(1,smooth(.5,.7,litN)*(cl===2?1.2:.95)+.45*smooth(.10,.35,curv)+.5*smooth(.05,.35,pw)*(1-smooth(.5,.9,pw)));
  const m=mound(x,z);rock*=1-.7*Math.min(1,m*2.5);litter*=1-.3*Math.min(1,m*2.5);
  let moss=Math.max(0,1-.85*rock-.8*litter)*(1-pw);rock*=1-pw;litter*=1-pw;
  const sum=moss+rock+litter+pw+1e-6;
  w[i*4]=moss/sum;w[i*4+1]=rock/sum;w[i*4+2]=litter/sum;w[i*4+3]=pw/sum;}
 g.setAttribute('aWeights',new THREE.BufferAttribute(w,4));
 return n;}
// ---------------------------------------------------------------- multi-layer world-space material (moss / basalt / litter / trail), anti-tiling, moss-on-top mode for rocks and logs
const groundMats={};const T={};
function loadTex(id,srgb,dir='assets/materials_v2'){const t=texloader.load(`${dir}/${id}`);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.anisotropy=Math.min(renderer.capabilities.getMaxAnisotropy(),8);if(srgb)t.colorSpace=THREE.SRGBColorSpace;return t;}
const LAYER_GLSL=`
uniform sampler2D tMossD,tMossN,tMossR,tRockD,tRockN,tRockR,tLitD,tLitN,tLitR,tPathD,tPathN,tPathR,tNoise;uniform float uMossAmount;uniform float uCanopyDark;
varying vec3 vWp;varying vec3 vWn;
#ifdef GROUND_WEIGHTS
varying vec4 vW;
#endif
vec4 sampleAT(sampler2D t,vec2 p,float scale,float seed){vec2 uv1=p/scale;float a=0.7+seed;mat2 R=mat2(cos(a),-sin(a),sin(a),cos(a));vec2 uv2=R*(p/(scale*1.37))+vec2(0.31,0.77)*seed;float m=texture2D(tNoise,p/32.0+vec2(seed*0.13,seed*0.07)).r;m=smoothstep(0.32,0.68,m);return mix(texture2D(t,uv1),texture2D(t,uv2),m);}
vec4 triplanar(sampler2D t,vec3 p,vec3 n,float scale,float seed){vec3 b=pow(abs(n),vec3(4.0));b/=(b.x+b.y+b.z);return sampleAT(t,p.zy,scale,seed)*b.x+sampleAT(t,p.xz,scale,seed)*b.y+sampleAT(t,p.xy,scale,seed)*b.z;}
vec4 layerWeights(vec3 n){
#ifdef GROUND_WEIGHTS
 vec4 w=vW;if(w.x+w.y+w.z+w.w<0.01){float l=0.18+smoothstep(0.55,0.8,texture2D(tNoise,vWp.xz/48.0).g)*0.5;w=vec4(1.0-l,0.06,l,0.0);}
#else
 float top=smoothstep(-0.1,0.75,n.y);float nz=texture2D(tNoise,vWp.xz/3.0+vWp.y*0.11).b;float moss=clamp(uMossAmount*(top*0.9+0.3)*(0.3+1.2*nz),0.0,1.0);vec4 w=vec4(moss,1.0-moss,0.0,0.0);
#endif
 vec3 nz3=texture2D(tNoise,vWp.xz/9.0).rgb;w.x*=0.7+0.6*nz3.r;w.y*=0.7+0.6*nz3.g;w.z*=0.7+0.6*nz3.b;w=pow(w,vec4(1.6));return w/max(1e-4,dot(w,vec4(1.0)));}`;
function layerMaterial(mode,base){// mode: 'ground' | 'rock' | 'log'
 const mat=new THREE.MeshStandardMaterial({map:T.mossD,normalMap:T.mossN,roughnessMap:T.mossR,roughness:1,metalness:0,normalScale:new THREE.Vector2(1,1)});
 mat.customProgramCacheKey=()=>'aoki-layers-'+mode;
 mat.onBeforeCompile=sh=>{Object.assign(sh.uniforms,{tMossD:{value:T.mossD},tMossN:{value:T.mossN},tMossR:{value:T.mossR},tRockD:{value:base?.d??T.rockD},tRockN:{value:base?.n??T.rockN},tRockR:{value:base?.r??T.rockR},tLitD:{value:T.litD},tLitN:{value:T.litN},tLitR:{value:T.litR},tPathD:{value:T.pathD},tPathN:{value:T.pathN},tPathR:{value:T.pathR},tNoise:{value:T.noise},uMossAmount:{value:mode==='log'?.7:.8},uCanopyDark:{value:1.0}});
  const pre=(mode==='ground'?'#define GROUND_WEIGHTS\n':'')+(mode==='log'?'#define BASE_UV\n':'');
  sh.vertexShader=pre+'varying vec3 vWp;varying vec3 vWn;\n#ifdef GROUND_WEIGHTS\nattribute vec4 aWeights;varying vec4 vW;\n#endif\n'+sh.vertexShader
   .replace('#include <defaultnormal_vertex>','#include <defaultnormal_vertex>\n{vec3 on=objectNormal;\n#ifdef USE_INSTANCING\non=mat3(instanceMatrix)*on;\n#endif\nvWn=normalize(mat3(modelMatrix)*on);}')
   .replace('#include <worldpos_vertex>','#include <worldpos_vertex>\n{vec4 wp4=vec4(transformed,1.0);\n#ifdef USE_INSTANCING\nwp4=instanceMatrix*wp4;\n#endif\nwp4=modelMatrix*wp4;vWp=wp4.xyz;}\n#ifdef GROUND_WEIGHTS\nvW=aWeights;\n#endif');
  sh.fragmentShader=pre+LAYER_GLSL+'\n'+sh.fragmentShader
   .replace('#include <map_fragment>',`
    vec3 gN=normalize(vWn);vec4 lw=layerWeights(gN);
    #ifdef GROUND_WEIGHTS
     vec4 mossD=sampleAT(tMossD,vWp.xz,1.0,1.0),rockD=sampleAT(tRockD,vWp.xz,1.5,2.0),litD=sampleAT(tLitD,vWp.xz,0.8,3.0),pathD=sampleAT(tPathD,vWp.xz,1.0,4.0);
     vec4 mossN=sampleAT(tMossN,vWp.xz,1.0,1.0),rockN=sampleAT(tRockN,vWp.xz,1.5,2.0),litN=sampleAT(tLitN,vWp.xz,0.8,3.0),pathN=sampleAT(tPathN,vWp.xz,1.0,4.0);
     vec4 mossR=sampleAT(tMossR,vWp.xz,1.0,1.0),rockR=sampleAT(tRockR,vWp.xz,1.5,2.0),litR=sampleAT(tLitR,vWp.xz,0.8,3.0),pathR=sampleAT(tPathR,vWp.xz,1.0,4.0);
    #else
     vec4 mossD=triplanar(tMossD,vWp,gN,0.9,1.0),mossN=triplanar(tMossN,vWp,gN,0.9,1.0),mossR=triplanar(tMossR,vWp,gN,0.9,1.0);
     #ifdef BASE_UV
      vec4 rockD=texture2D(tRockD,vMapUv),rockN=texture2D(tRockN,vMapUv),rockR=texture2D(tRockR,vMapUv);
     #else
      vec4 rockD=triplanar(tRockD,vWp,gN,1.4,2.0),rockN=triplanar(tRockN,vWp,gN,1.4,2.0),rockR=triplanar(tRockR,vWp,gN,1.4,2.0);
     #endif
     vec4 litD=vec4(0.0),litN=vec4(0.5,0.5,1.0,1.0),litR=vec4(0.9),pathD=vec4(0.0),pathN=litN,pathR=litR;
    #endif
    // height-ish sharpening: brighter (raised) moss cushions win over lower layers
    float mossH=mossD.g*1.3;lw.x*=0.35+mossH;lw/=max(1e-4,dot(lw,vec4(1.0)));
    vec3 hue=texture2D(tNoise,vWp.xz/48.0).rgb;vec3 mossTint=vec3(0.85+0.3*hue.r,0.95+0.15*hue.g,0.8+0.35*hue.b);
    float canopy=(0.8+0.2*texture2D(tNoise,vWp.xz/24.0+vec2(0.5)).g)*uCanopyDark;
    vec4 alb=mossD*vec4(mossTint,1.0)*lw.x+rockD*lw.y+litD*lw.z+pathD*lw.w;
    diffuseColor*=vec4(alb.rgb*canopy,1.0);
    vec3 blendedN=normalize((mossN.xyz*2.0-1.0)*lw.x+(rockN.xyz*2.0-1.0)*lw.y+(litN.xyz*2.0-1.0)*lw.z+(pathN.xyz*2.0-1.0)*lw.w);
    float blendedR=mossR.g*lw.x+rockR.g*lw.y+litR.g*lw.z+pathR.g*lw.w;`)
   .replace('#include <roughnessmap_fragment>','float roughnessFactor=roughness*clamp(blendedR,0.35,1.0);')
   .replace('#include <normal_fragment_maps>','{vec3 mapN=blendedN;mapN.xy*=normalScale;normal=normalize(tbn*mapN);}');
  mat.userData.shader=sh;};
 return mat;}
async function materials(){const L=(id,s)=>loadTex(id,s);T.mossD=L('moss_diff_1k.jpg',1);T.mossN=L('moss_nor_gl_1k.jpg');T.mossR=L('moss_rough_1k.jpg');T.rockD=L('basalt_diff_1k.jpg',1);T.rockN=L('basalt_nor_gl_1k.jpg');T.rockR=L('basalt_rough_1k.jpg');T.litD=L('litter_diff_1k.jpg',1);T.litN=L('litter_nor_gl_1k.jpg');T.litR=L('litter_rough_1k.jpg');T.pathD=L('trail_diff_1k.jpg',1);T.pathN=L('trail_nor_gl_1k.jpg');T.pathR=L('trail_rough_1k.jpg');T.noise=L('blend_noise_512.png');
 groundMats.ground=layerMaterial('ground');groundMats.ground.name='Near-field ground layers: procedural moss/basalt/litter/trail (PROCEDURAL, not site-captured)';groundMats.rock=layerMaterial('rock');groundMats.rock.name='Procedural lava block: basalt with moss on upper faces';// The base terrain and the near-field patch are the same forest floor at two sampling rates, so
// they must shade identically. The canopy term is already spatial — (0.8 + 0.2 * world noise) —
// and therefore continuous on its own; the base material previously scaled it by a further 0.62,
// which is a 38% albedo step along an edge that follows the camera. One value serves both.
groundMats.base=layerMaterial('ground');groundMats.base.name='Base terrain: moss/basalt/litter/trail layers (same model as the near-field patch)';}
// ---------------------------------------------------------------- base path ribbons outside the near-field patch
function clipSegment(a,b,r){if(!r)return [a,b];const dx=b[0]-a[0],dz=b[1]-a[1],pp=[-dx,dx,-dz,dz],qq=[a[0]-r[0],r[2]-a[0],a[1]-r[1],r[3]-a[1]];let lo=0,hi=1;for(let i=0;i<4;i++){if(pp[i]===0){if(qq[i]<0)return null;}else{const t=qq[i]/pp[i];if(pp[i]<0)lo=Math.max(lo,t);else hi=Math.min(hi,t);if(lo>hi)return null;}}return [[a[0]+lo*dx,a[1]+lo*dz],[a[0]+hi*dx,a[1]+hi*dz]];}
function buildPaths(ctx,group=pathGroup,bounds=null,mat=null){const positions=[],uv=[],idx=[];for(const p of ctx.paths){if(p.access==='private'||p.access==='no')continue;const width=p.kind==='road'?6.8:1.7;for(let k=1;k<p.coordinates.length;k++){const clipped=clipSegment(p.coordinates[k-1],p.coordinates[k],bounds);if(!clipped)continue;const [a,b]=clipped;const dx=b[0]-a[0],dz=b[1]-a[1],len=Math.hypot(dx,dz);if(len<.01)continue;const px=-dz/len*width/2,pz=dx/len*width/2,steps=Math.ceil(len/(bounds?.8:1)),start=positions.length/3;for(let q=0;q<=steps;q++){const x=a[0]+dx*q/steps,z=a[1]+dz*q/steps;for(const s of[-1,1]){const gx=x+px*s,gz=z+pz*s;positions.push(gx,(sample(gx,gz)??0)+.06,gz);uv.push(gx,gz);}}for(let q=0;q<steps;q++){let t=start+2*q;idx.push(t,t+1,t+2,t+1,t+3,t+2);}}}if(!positions.length)return;const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));g.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));g.setIndex(idx);g.computeVertexNormals();const mesh=new THREE.Mesh(g,mat||pathMat);mesh.name='OSM mapped centre lines; widths and materials approximated';mesh.receiveShadow=true;group.add(mesh);}
let pathMat;
// ---------------------------------------------------------------- stand structure: instance augmentation (size classes, snags, tilt) — PROCEDURAL, ecologically motivated (ECO-001/002), not a census
const V2={0:'tsuga_a',1:'tsuga_b',2:'tsuga_c',3:'hinoki_a',4:'hinoki_b',5:'hinoki_c',6:'snag_a',7:'snag_b',8:'tree_2',9:'tree_3'};
function augmentForest(){const n=forestData.length/6;forestAug=new Float32Array(n*4);for(let q=0;q<n;q++){const i=Math.round(forestData[q*6]*10),j=Math.round(forestData[q*6+2]*10),cl=forestData[q*6+5];let s=forestData[q*6+3];const r=rand(i,j,301);s*=r<.22?.55+.3*rand(i,j,302):r<.88?.85+.35*rand(i,j,303):1.12+.25*rand(i,j,304);
  let v;const rs=rand(i,j,305);if(rand(i,j,306)<.06)v=6+Math.floor(rand(i,j,307)*2);else if(cl>=2)v=rs<.5?8+Math.floor(rand(i,j,308)*2):rs<.75?Math.floor(rand(i,j,309)*3):3+Math.floor(rand(i,j,309)*3);else v=rs<.52?Math.floor(rand(i,j,310)*3):3+Math.floor(rand(i,j,310)*3);
  forestAug[q*4]=s;forestAug[q*4+1]=(rand(i,j,311)-.5)*.09;forestAug[q*4+2]=(rand(i,j,312)-.5)*.09;forestAug[q*4+3]=v;const key=Math.floor(forestData[q*6]/10)+','+Math.floor(forestData[q*6+2]/10);if(!treeGrid.has(key))treeGrid.set(key,[]);treeGrid.get(key).push(q*6);}}
function collectTrees(){const x=camera.position.x,z=camera.position.z,alt=camera.position.y-(sample(x,z)??0),radius=alt>100?1600:(quality==='high'?460:360),arr=[];for(let q=0;q<forestData.length;q+=6){const dx=forestData[q]-x,dz=forestData[q+2]-z,d=Math.hypot(dx,dz);if(d>radius)continue;if(d>600&&rand(q,0,2)>.18)continue;const a=q/6*4;arr.push([forestData[q],forestData[q+1],forestData[q+2],forestAug[a],forestData[q+4],forestAug[a+3],d,forestAug[a+1],forestAug[a+2]]);}
 if(Math.abs(x)>700||Math.abs(z)>700){const r=Math.min(radius,500),ii=Math.floor(x/8.5),jj=Math.floor(z/8.5),c=Math.ceil(r/8.5);for(let j=jj-c;j<=jj+c;j++)for(let i=ii-c;i<=ii+c;i++){const tx=i*8.5+(rand(i,j,1)-.5)*5.8,tz=j*8.5+(rand(i,j,2)-.5)*5.8;if(Math.abs(tx)<=1024&&Math.abs(tz)<=1024)continue;const d=Math.hypot(tx-x,tz-z);if(d>r)continue;const cl=landclass(tx,tz);if(![1,2,3].includes(cl)||rand(i,j,8)<.045||onPath(tx,tz))continue;const v=cl===2?(rand(i,j,4)<.5?8:3):Math.floor(rand(i,j,4)*6);arr.push([tx,sample(tx,tz)-.06,tz,.72+rand(i,j,5)*.5,rand(i,j,6)*Math.PI*2,v,d,0,0]);}}
 return arr.sort((a,b)=>a[6]-b[6]);}
// small stems (regeneration / sub-canopy, 1.5–6 m): densify gaps between mature stems. PROCEDURAL.
function collectSmall(){const x=camera.position.x,z=camera.position.z,out=[];if(camera.position.y-(sample(x,z)??0)>40)return out;const R=quality==='high'?130:110,cs=3.6,ii=Math.floor(x/cs),jj=Math.floor(z/cs),c=Math.ceil(R/cs);for(let j=jj-c;j<=jj+c;j++)for(let i=ii-c;i<=ii+c;i++){const tx=i*cs+(rand(i,j,401)-.5)*3.6,tz=j*cs+(rand(i,j,402)-.5)*3.6,d=Math.hypot(tx-x,tz-z);if(d>R||Math.abs(tx)>1024||Math.abs(tz)>1024)continue;if(![1,2,3].includes(landclass(tx,tz))||pathWeight(tx,tz)>.12)continue;const dens=fbm(tx/22,tz/22,410,3);let near=99;for(const q of nearTrees(tx,tz,4)){near=Math.min(near,Math.hypot(forestData[q]-tx,forestData[q+2]-tz));}const p=(.22+.6*smooth(.35,.75,dens))*(near<1.4?.15:near<3?.65:1.1);if(rand(i,j,403)>p)continue;const r=rand(i,j,404),v=r<.4?'sap_tsuga':r<.75?'sap_hinoki':'sap_small';out.push([tx,tz,.6+rand(i,j,405)*.9,rand(i,j,406)*6.283,v,d]);}
 // sub-canopy stems (7–13 m): mature forms at reduced scale filling gaps; clustered. PROCEDURAL stand densification.
 const R2=quality==='high'?230:170,cs2=6.0,i2=Math.floor(x/cs2),j2=Math.floor(z/cs2),c2=Math.ceil(R2/cs2);for(let j=j2-c2;j<=j2+c2;j++)for(let i=i2-c2;i<=i2+c2;i++){const tx=i*cs2+(rand(i,j,421)-.5)*5,tz=j*cs2+(rand(i,j,422)-.5)*5,d=Math.hypot(tx-x,tz-z);if(d>R2||Math.abs(tx)>1024||Math.abs(tz)>1024)continue;const cl=landclass(tx,tz);if(![1,2,3].includes(cl)||pathWeight(tx,tz)>.08)continue;const dens=fbm(tx/30,tz/30,430,3);let near=99;for(const q of nearTrees(tx,tz,4)){near=Math.min(near,Math.hypot(forestData[q]-tx,forestData[q+2]-tz));}const p=(.4+.55*smooth(.3,.75,dens))*(near<2.2?.1:near<3.5?.5:1);if(rand(i,j,423)>p)continue;const r=rand(i,j,424),v=cl===2&&r<.35?(r<.17?'tree_2':'tree_3'):r<.6?'tsuga_c':'hinoki_c';out.push([tx,tz,.42+rand(i,j,425)*.33,rand(i,j,426)*6.283,v,d]);}
 return out;}
function clearInstances(group){for(const o of [...group.children]){group.remove(o);if(o.isInstancedMesh){o.dispose();}else if(o.userData.disposable){o.geometry.dispose();}}}
const tmpObj=new THREE.Object3D();
function addInstanced(group,protoName,list,placeFn,shadow){const proto=lib[protoName];if(!proto||!list.length)return;for(const part of proto){const m=new THREE.InstancedMesh(part.geometry,part.material,list.length);m.name=`${protoName} ×${list.length}`;list.forEach((t,j)=>{placeFn(t,tmpObj);tmpObj.updateMatrix();m.setMatrixAt(j,tmpObj.matrix);});m.castShadow=shadow;m.receiveShadow=true;m.instanceMatrix.needsUpdate=true;m.computeBoundingSphere();m.frustumCulled=true;group.add(m);}}
function rebuildForest(force=false){if(!force&&lastForest.distanceTo(camera.position)<18)return;lastForest.copy(camera.position);
 if(Math.max(Math.abs(camera.position.x-patchCX),Math.abs(camera.position.z-patchCZ))>12&&Math.abs(camera.position.x)<1000&&Math.abs(camera.position.z)<1000)buildGroundPatch(camera.position.x,camera.position.z);
 clearInstances(forestGroup);trees=collectTrees();small=collectSmall();heroTrees=matureTemplate?trees.filter(t=>t[5]<6&&t[6]<26).slice(0,quality==='high'?5:3):[];
 const HR=quality==='high'?62:46,buckets={};for(const t of trees){if(heroTrees.includes(t))continue;const v=V2[t[5]];const lod=t[6]<HR?'high':t[6]<230?'low':'far';const key=`${v}_${v.startsWith('tree_')&&lod==='far'?'low':lod}`;if(!lib[key])continue;(buckets[key]??=[]).push(t);}
 for(const [key,arr]of Object.entries(buckets)){const cap=key.endsWith('high')?260:key.endsWith('low')?2600:6000;addInstanced(forestGroup,key,arr.slice(0,cap),(t,o)=>{const y=t[6]<70?groundY(t[0],t[2])-.10*t[3]:t[1];o.position.set(t[0],y,t[2]);o.rotation.set(t[7],t[4],t[8]);o.scale.setScalar(t[3]);},key.endsWith('high'));}
 const sb={};for(const s of small){const sap=s[4].startsWith('sap');const lod=sap?(s[5]<(quality==='high'?30:22)?'high':'low'):(s[5]<HR?'high':'low');(sb[`${s[4]}_${lod}`]??=[]).push(s);}
 for(const [key,arr]of Object.entries(sb))addInstanced(forestGroup,key,arr,(s,o)=>{o.position.set(s[0],groundY(s[0],s[1])-.04,s[1]);o.rotation.set(0,s[3],0);o.scale.setScalar(s[2]);},key.endsWith('high'));
 rebuildDecor();if(Math.abs(camera.position.x)>750||Math.abs(camera.position.z)>750){for(const o of [...pathGroup.children]){pathGroup.remove(o);o.geometry.dispose();}buildPaths(contexts.study,pathGroup,[camera.position.x-400,camera.position.z-400,camera.position.x+400,camera.position.z+400]);}}
// ---------------------------------------------------------------- near-field decor: lava blocks, ferns, fallen logs, hero mature firs
const rockGeos=[];function makeRockGeo(seed){const g=new THREE.IcosahedronGeometry(1,4);const a=g.attributes.position;const rng=k=>rand(seed,k,55);const f=.55+.35*rng(1),g2=.7+.3*rng(2);for(let i=0;i<a.count;i++){let x=a.getX(i),y=a.getY(i),z=a.getZ(i);const m=Math.max(Math.abs(x),Math.abs(y),Math.abs(z));const k=Math.pow(m,-.45);x*=k;y*=k;z*=k;const n=(fbm(x*1.7+seed,z*1.7+y*.9,960,3)-.5)*.5+(vn(x*6+seed,y*6+z*3,961)-.5)*.16+(vn(x*14+seed,y*14+z*7,962)-.5)*.05;const r=1+n;a.setXYZ(i,x*r*g2,y*r*f,z*r);}g.computeVertexNormals();g.computeBoundingSphere();const uv=new Float32Array(a.count*2);for(let i=0;i<a.count;i++){uv[i*2]=a.getX(i);uv[i*2+1]=a.getZ(i);}g.setAttribute('uv',new THREE.BufferAttribute(uv,2));return g;}
function clonePlaced(proto,x,z,scale=1,rot=0){const c=proto.clone(true);c.position.set(0,0,0);c.rotation.set(0,rot,0);c.scale.setScalar(scale);const box=new THREE.Box3().setFromObject(c);c.position.set(x,(groundY(x,z)??0)-box.min.y-.03,z);c.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;}});decorGroup.add(c);return c;}
function rebuildDecor(){clearInstances(decorGroup);for(const t of heroTrees)clonePlaced(matureTemplate,t[0],t[2],t[3],t[4]);const x=camera.position.x,z=camera.position.z;if(camera.position.y-(sample(x,z)??0)>60)return;
 const rocks=[],ferns=[[],[],[],[]],logs=[];const R=quality==='high'?52:42;
 for(let j=-Math.ceil(R/2.5);j<=Math.ceil(R/2.5);j++)for(let i=-Math.ceil(R/2.5);i<=Math.ceil(R/2.5);i++){const ix=Math.floor(x/2.5)+i,iz=Math.floor(z/2.5)+j,tx=ix*2.5+(rand(ix,iz,19)-.5)*2.2,tz=iz*2.5+(rand(ix,iz,20)-.5)*2.2,d=Math.hypot(tx-x,tz-z);if(d>R||Math.abs(tx)>1024||Math.abs(tz)>1024||![1,2,3].includes(landclass(tx,tz)))continue;const pw=pathWeight(tx,tz);const rockN=fbm(tx/5.5,tz/5.5,940,3),fernN=fbm(tx/9,tz/9,970,3);
  if(rand(ix,iz,32)<.25+.5*smooth(.45,.8,rockN)+.2*pw)for(let q=0;q<1+Math.floor(rand(ix,iz,33)*2);q++){const sx=tx+(rand(ix,iz,34+q)-.5)*2.2,sz=tz+(rand(ix,iz,36+q)-.5)*2.2;rocks.push([sx,sz,.10+Math.pow(rand(ix,iz,38+q),1.5)*.3,rand(ix,iz,40+q)*6.28,Math.floor(rand(ix,iz,42+q)*rockGeos.length)]);}
  if(pw>.15)continue;
  if(rand(ix,iz,21)<.24+.7*smooth(.45,.8,fernN))ferns[Math.floor(rand(ix,iz,27)*4)].push([tx,tz,.7+rand(ix,iz,22)*.8,rand(ix,iz,23)*6.28]);
  if(rand(ix,iz,24)<.10+.45*smooth(.5,.8,rockN))rocks.push([tx,tz,.28+Math.pow(rand(ix,iz,25),2.2)*1.6,rand(ix,iz,26)*6.28,Math.floor(rand(ix,iz,28)*rockGeos.length)]);
  if(logGeo&&rand(ix,iz,29)<.016&&d<R*.85)logs.push([tx,tz,.7+rand(ix,iz,30)*.6,rand(ix,iz,31)*6.28]);}
 for(let k=0;k<rockGeos.length;k++){const list=rocks.filter(r=>r[4]===k);if(!list.length)continue;const m=new THREE.InstancedMesh(rockGeos[k],groundMats.rock,list.length);m.name='Procedural lava blocks (PROCEDURAL; moss on upper faces)';list.forEach((a,i)=>{tmpObj.position.set(a[0],groundY(a[0],a[1])-.28*a[2],a[1]);tmpObj.rotation.set((rand(i,k,61)-.5)*.5,a[3],(rand(i,k,62)-.5)*.5);tmpObj.scale.set(a[2]*(.8+.4*rand(i,k,63)),a[2],a[2]*(.8+.4*rand(i,k,64)));tmpObj.updateMatrix();m.setMatrixAt(i,tmpObj.matrix);});m.castShadow=m.receiveShadow=true;m.instanceMatrix.needsUpdate=true;decorGroup.add(m);}
 fernProto.forEach((p,k)=>{const list=ferns[k];if(!list.length)return;const m=new THREE.InstancedMesh(p.geometry,p.material,list.length);m.name='Representative fern (Poly Haven fern_02, CC0; species not verified)';list.forEach((a,i)=>{tmpObj.position.set(a[0],groundY(a[0],a[1])-p.userData.minY*a[2]-.02,a[1]);tmpObj.rotation.set(0,a[3],0);tmpObj.scale.setScalar(a[2]);tmpObj.updateMatrix();m.setMatrixAt(i,tmpObj.matrix);});m.castShadow=false;m.receiveShadow=true;m.instanceMatrix.needsUpdate=true;decorGroup.add(m);});
 if(logGeo&&logs.length){const m=new THREE.InstancedMesh(logGeo,logMat,logs.length);m.name='Fallen timber (Poly Haven dead_tree_trunk, CC0; moss overlay procedural)';logs.forEach((a,i)=>{const dirx=Math.cos(a[3]),dirz=Math.sin(a[3]);const y0=groundY(a[0]-dirx*2,a[1]-dirz*2),y1=groundY(a[0]+dirx*2,a[1]+dirz*2);tmpObj.position.set(a[0],(y0+y1)/2-.10*a[2],a[1]);tmpObj.rotation.set(0,-a[3],Math.atan2(y1-y0,4)*.8);tmpObj.scale.setScalar(a[2]);tmpObj.updateMatrix();m.setMatrixAt(i,tmpObj.matrix);});m.castShadow=m.receiveShadow=true;m.instanceMatrix.needsUpdate=true;decorGroup.add(m);}}
function addWater(ctx){const mat=new THREE.MeshPhysicalMaterial({color:0x4e7775,roughness:.25,metalness:.06,transparent:true,opacity:.87});for(const l of ctx.lakes){const coords=l.geometry?.coordinates;if(!coords)continue;const polygons=l.geometry.type==='MultiPolygon'?coords:[coords];for(const p of polygons){const shape=new THREE.Shape(p[0].map(c=>new THREE.Vector2(c[0],-c[1])));for(const hole of p.slice(1))shape.holes.push(new THREE.Path(hole.map(c=>new THREE.Vector2(c[0],-c[1]))));const g=new THREE.ShapeGeometry(shape);g.rotateX(-Math.PI/2);const m=new THREE.Mesh(g,mat);m.position.y=(l.waterElevationM??l.elevationM??900)-900+.2;m.name='Lake surface estimate, not bathymetry';scene.add(m);}}}
function protoMeshes(model){const out=[];model.updateMatrixWorld(true);model.traverse(n=>{if(n.isMesh){const c=n.clone();c.position.set(0,0,0);c.rotation.set(0,0,0);c.scale.set(1,1,1);const mats=Array.isArray(c.material)?c.material:[c.material];for(const m of mats){m.side=THREE.DoubleSide;if(m.transparent||m.alphaTest>0){m.alphaTest=Math.max(m.alphaTest||0,.35);m.transparent=false;}m.roughness=Math.max(m.roughness??1,.85);}c.geometry.computeBoundingBox();c.userData.minY=c.geometry.boundingBox.min.y;out.push(c);}});return out;}
// foliage: no dark underside — thin conifer sprays read as partly translucent, so light both faces toward world-up
function foliageMaterialFix(m){m.side=THREE.DoubleSide;m.alphaTest=.3;m.alphaToCoverage=true;m.transparent=false;m.vertexColors=true;m.roughness=.9;m.customProgramCacheKey=()=>'aoki-foliage';m.onBeforeCompile=sh=>{sh.fragmentShader=sh.fragmentShader.replace('#include <normal_fragment_begin>','#include <normal_fragment_begin>\n{vec3 upV=normalize((viewMatrix*vec4(0.0,1.0,0.0,0.0)).xyz);normal=normalize(mix(normal*faceDirection,upV,0.5));\n#if defined( USE_NORMALMAP_TANGENTSPACE )\ntbn=getTangentFrame(-vViewPosition,normal,vNormalMapUv);\n#endif\n}');};m.needsUpdate=true;}
function indexLibrary(model,target){const seen=new Set();model.traverse(o=>{if(!o.isMesh)return;const mats=Array.isArray(o.material)?o.material:[o.material];for(const m of mats){if(seen.has(m))continue;seen.add(m);m.vertexColors=true;if(m.alphaTest>0||m.transparent)foliageMaterialFix(m);else{m.side=THREE.FrontSide;m.roughness=1;}}});for(const node of model.children){const parts=[];node.traverse(o=>{if(o.isMesh)parts.push(o);});if(parts.length)target[node.name]=parts;}}
async function init(){try{status('Loading measured terrain and mapped communities…',10);await Promise.all(['local','study','regional'].map(getGrid));[contexts.local,contexts.study]=await Promise.all(['local','study'].map(n=>json(`assets/terrain/${n}-context.json`)));await materials();pathMat=new THREE.MeshStandardMaterial({map:T.pathD,normalMap:T.pathN,roughnessMap:T.pathR,roughness:1});pathMat.name='Trail surface (procedural compacted cinder/soil)';
 status('Preparing the forest…',30);forestMeta=await json('assets/forest-instances.json');forestData=new Float32Array(await fetch('assets/forest-instances.f32').then(r=>r.arrayBuffer()));initSegments(contexts.study);augmentForest();
 const [surface,lib2,libOld,fern,log,mature]=await Promise.all([glb('../models/Aokigahara_Surface_Terrain.glb'),glb('assets/tree-library-v2.glb'),glb('assets/tree-library.glb'),glb('assets/models/fern_02.glb'),glb('assets/models/dead_tree_trunk.glb'),glb('assets/models/fir_tree_c.glb')]);
 const baseGround=[];
 surface.traverse(o=>{if(o.isMesh){o.geometry.computeBoundsTree();o.receiveShadow=true;let mat=o.material;if(mat.name.includes('Local_Ground')){o.material=groundMats.base;o.name='GSI DEM corridor terrain (8 m resample); base ground layers';baseGround.push(o);}else{mat.roughness=1;mat.metalness=0;mat.color.multiplyScalar(.6);}}});scene.add(surface);surface.updateMatrixWorld(true);surfaceModel=surface;matureTemplate=mature;
 status('Deriving ground layers beyond the near field…',80);let baseVerts=0;for(const o of baseGround)baseVerts+=buildBaseWeights(o);console.info(`Base ground layer weights: ${baseVerts} vertices across ${baseGround.length} mesh(es)`);
 mature.traverse(o=>{if(o.isMesh){const mats=Array.isArray(o.material)?o.material:[o.material];for(const m of mats){if(m.alphaTest>0||m.transparent){m.alphaTest=.35;m.transparent=false;m.alphaToCoverage=true;}m.roughness=Math.max(m.roughness??1,.85);}}});
 indexLibrary(lib2,lib);indexLibrary(libOld,lib);for(const k of Object.keys(lib))if(k.startsWith('tree_')){for(const p of lib[k]){if(p.material.name.includes('leaves')){p.material.color.setRGB(.55,.62,.42);p.material.roughness=.95;}}}
 fernProto=protoMeshes(fern);const logParts=protoMeshes(log);if(logParts.length){logGeo=logParts[0].geometry;const lm=logParts[0].material;logMat=layerMaterial('log',{d:lm.map,n:lm.normalMap,r:lm.roughnessMap});logMat.name='Fallen log: dead_tree_trunk (CC0) + procedural moss overlay';}
 for(let k=0;k<5;k++)rockGeos.push(makeRockGeo(k*17+3));
 buildPaths(contexts.local);addWater(contexts.study);status('Opening the Fugaku forest corridor…',88);camera.position.set(32.14,0,-9.84);buildGroundPatch(32.14,-9.84);camera.position.y=groundY(32.14,-9.84)+1.72;camera.rotation.set(pitch,yaw,0);setSun();rebuildForest(true);ready=true;$('loading').style.opacity='0';setTimeout(()=>$('loading').style.display='none',650);updateLocation();animate();}catch(e){console.error(e);$('load-message').textContent='The landscape could not finish loading. Reload to retry, or download the GLB files.';$('menu-button').onclick=()=>{$('loading').style.display='none';$('panel').hidden=false;};}}
// ---------------------------------------------------------------- navigation
const keys=new Set();let movePad={x:0,y:0},vertical=0;const clock=new THREE.Clock();let uiTimer=0;
function tick(dt){const isPanel=!$('panel').hidden;if(entered&&!isPanel){let forward=(keys.has('KeyW')||keys.has('ArrowUp')?1:0)-(keys.has('KeyS')||keys.has('ArrowDown')?1:0)-movePad.y;let side=(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0)+movePad.x;const len=Math.max(1,Math.hypot(forward,side));forward/=len;side/=len;const speed=(mode==='fly'?(keys.has('ShiftLeft')?170:45):(keys.has('ShiftLeft')?4.6:1.9))*dt;const dx=(-Math.sin(yaw)*forward+Math.cos(yaw)*side)*speed,dz=(-Math.cos(yaw)*forward-Math.sin(yaw)*side)*speed;let nx=THREE.MathUtils.clamp(camera.position.x+dx,-13860,17860),nz=THREE.MathUtils.clamp(camera.position.z+dz,-10860,18860);if(mode==='walk'){let hit=false;for(const t of trees){if(t[6]>25)break;if(Math.hypot(nx-t[0],nz-t[2])<.28*t[3]+.15){hit=true;break;}}if(!hit){camera.position.x=nx;camera.position.z=nz;}const y=groundY(camera.position.x,camera.position.z);if(y!==null)camera.position.y=THREE.MathUtils.lerp(camera.position.y,y+1.72,Math.min(1,dt*10));}else{camera.position.x=nx;camera.position.z=nz;const up=(keys.has('Space')||keys.has('KeyE')?1:0)-(keys.has('ControlLeft')||keys.has('KeyQ')?1:0)+vertical;camera.position.y+=up*speed-Math.sin(pitch)*forward*speed;camera.position.y=Math.max(camera.position.y,(groundY(nx,nz)??0)+1.5);}}
 camera.rotation.set(pitch,yaw,0);rebuildForest();if(lastShadow.distanceTo(camera.position)>6){lastShadow.copy(camera.position);sun.target.position.copy(camera.position);sun.position.copy(camera.position).addScaledVector(sunVector,110);sun.target.updateMatrixWorld();}
 const alt=camera.position.y-(sample(camera.position.x,camera.position.z)??0);scene.fog.density=(.0022+Number($('haze').value)*.00004)/(1+Math.max(0,alt-40)/220);}
function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.045);tick(dt);uiTimer+=dt;if(uiTimer>.3){updateLocation();uiTimer=0;}renderer.render(scene,camera);}
function updateLocation(){const bearing=((THREE.MathUtils.radToDeg(yaw)*-1)%360+360)%360;$('bearing').textContent=`${Math.round(bearing).toString().padStart(3,'0')}°`;$('position').textContent=`${mode==='walk'?'Walking':'Flying'} · ${(camera.position.y+900).toFixed(0)} m elevation · E ${camera.position.x.toFixed(0)} / S ${camera.position.z.toFixed(0)} m`;}
$('menu-button').onclick=()=>{$('panel').hidden=false;document.exitPointerLock?.();};$('close-panel').onclick=()=>{$('panel').hidden=true;};
function enter(){canvas.focus();entered=true;$('start-hint').style.display='none';if(!matchMedia('(pointer:coarse)').matches){try{const p=canvas.requestPointerLock?.();p?.catch(()=>toast('Drag the landscape to look around.'));}catch(e){toast('Drag the landscape to look around.');}}}
$('enter').onclick=enter;canvas.addEventListener('click',()=>{if(ready&&$('panel').hidden&&document.pointerLockElement!==canvas)enter();});
window.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(document.activeElement?.tagName)&&!['Escape'].includes(e.code))return;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();keys.add(e.code);if(e.code==='Escape'){$('panel').hidden=true;keys.clear();}if(e.code==='KeyF')setMode(mode==='walk'?'fly':'walk');});window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>keys.clear());
function rotate(dx,dy){yaw-=dx*.0022;pitch=THREE.MathUtils.clamp(pitch-dy*.0022,-1.47,1.47);}
window.addEventListener('mousemove',e=>{if(document.pointerLockElement===canvas)rotate(e.movementX,e.movementY);});canvas.addEventListener('pointerdown',e=>{canvas.focus();if(document.pointerLockElement===canvas||!$('panel').hidden)return;lookDragging=true;previousPointer=[e.clientX,e.clientY];canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(lookDragging&&document.pointerLockElement!==canvas){rotate(e.clientX-previousPointer[0],e.clientY-previousPointer[1]);previousPointer=[e.clientX,e.clientY];}});canvas.addEventListener('pointerup',()=>lookDragging=false);
function setMode(m){mode=m;$('walk').classList.toggle('selected',m==='walk');$('fly').classList.toggle('selected',m==='fly');if(m==='walk')camera.position.y=groundY(camera.position.x,camera.position.z)+1.72;toast(m==='fly'?'Fly: WASD · E / Space up · Q / Ctrl down · Shift faster':'Walk: WASD / arrows · Shift faster');}
$('walk').onclick=()=>setMode('walk');$('fly').onclick=()=>setMode('fly');$('quality').onchange=async()=>{quality=$('quality').value;renderer.setPixelRatio(Math.min(devicePixelRatio,quality==='high'?2:1.5));rebuildForest(true);};
$('sun').oninput=setSun;
// Single entry point for the daylight presets, so the panel control, the destination
// jumps and the headless audit hook can never disagree about which preset is live.
function applyPreset(p,angle){if(!PRESETS[p])return;preset=p;if(angle!==undefined)$('sun').value=angle;const sel=$('light');if(sel&&sel.value!==p)sel.value=p;setSun();}
const lightSel=$('light');if(lightSel){lightSel.value=preset;lightSel.onchange=()=>applyPreset(lightSel.value);}
const destinations={forest:[32.14,-9.84,1.72,.45,-.025,'Fugaku forest corridor'],fugaku:[-38,-18,1.72,-2.8,-.05,'Fugaku Wind Cave surface approach'],narusawa:[785,284,1.72,.7,-.06,'Narusawa Ice Cave surface approach'],img013:[-100.4,-197.6,1.72,1.5435,-.06,'Reference viewpoint IMG-013 (published camera geotag, heading 271.6°)'],saiko:[1100,-2400,560,Math.PI,-.24,'Saiko and the Jogan landscape'],fuji:[-3600,-4100,2900,Math.PI+.51,-.2,'Mount Fuji regional landscape']};
$('destination').onchange=()=>{const d=destinations[$('destination').value];camera.position.set(d[0],0,d[1]);if(Math.abs(d[0])<1000&&Math.abs(d[1])<1000)buildGroundPatch(d[0],d[1]);camera.position.y=(groundY(d[0],d[1])??0)+d[2];yaw=d[3];pitch=d[4];mode=d[2]>2?'fly':'walk';$('walk').classList.toggle('selected',mode==='walk');$('fly').classList.toggle('selected',mode==='fly');$('location').textContent=d[5];rebuildForest(true);$('panel').hidden=true;entered=true;$('start-hint').style.display='none';if(['fugaku','narusawa'].includes($('destination').value))toast('Surface reference location. Cave mouths and underground passages require a measured survey.');};
const pad=$('move-pad');let padOrigin;pad.onpointerdown=e=>{entered=true;$('start-hint').style.display='none';padOrigin=[e.clientX,e.clientY];pad.setPointerCapture(e.pointerId);};pad.onpointermove=e=>{if(!padOrigin)return;movePad.x=THREE.MathUtils.clamp((e.clientX-padOrigin[0])/42,-1,1);movePad.y=THREE.MathUtils.clamp((e.clientY-padOrigin[1])/42,-1,1);pad.firstElementChild.style.transform=`translate(${movePad.x*30}px,${movePad.y*30}px)`;};pad.onpointerup=pad.onpointercancel=()=>{padOrigin=null;movePad={x:0,y:0};pad.firstElementChild.style.transform='';};let lookOrigin;const lp=$('look-pad');lp.onpointerdown=e=>{lookOrigin=[e.clientX,e.clientY];lp.setPointerCapture(e.pointerId);};lp.onpointermove=e=>{if(!lookOrigin)return;rotate(e.clientX-lookOrigin[0],e.clientY-lookOrigin[1]);lookOrigin=[e.clientX,e.clientY];};lp.onpointerup=lp.onpointercancel=()=>lookOrigin=null;for(const [id,v]of[['rise',1],['fall',-1]]){$(id).onpointerdown=()=>vertical=v;$(id).onpointerup=$(id).onpointerleave=()=>vertical=0;}
$('download-model').onclick=async e=>{e.preventDefault();const a=$('download-model'),label=a.textContent;a.textContent='Preparing download…';try{const m=await json('assets/corridor-download.json'),chunks=[];let done=0;for(const p of m.parts){const r=await fetch('assets/'+p.file);if(!r.ok)throw new Error('Download failed');const b=await r.arrayBuffer();if(b.byteLength!==p.bytes)throw new Error('Incomplete file part');chunks.push(b);done+=b.byteLength;a.textContent=`Downloading ${Math.round(done/m.bytes*100)}%`; }const url=URL.createObjectURL(new Blob(chunks,{type:m.mimeType})),link=document.createElement('a');link.href=url;link.download=m.fileName;link.click();setTimeout(()=>URL.revokeObjectURL(url),60000);toast('Model download ready. Keep the source information with it.');}catch(err){toast('The model download was interrupted. Try again.');}finally{a.textContent=label;}};
// Patch export: the near-field ground (with relief), trees, small stems and decor around the camera as editable nodes. Custom layered shading is exported as its moss base layer (glTF has no multi-layer material).
$('export-patch').onclick=async()=>{const btn=$('export-patch');btn.disabled=true;btn.textContent='Preparing 120 m patch…';toast('Preparing a standard GLB with relief ground, individual tree nodes and decor.');await new Promise(r=>setTimeout(r,50));try{const g=new THREE.Group();g.name='Aokigahara near-field patch';g.userData={georeference:'WGS84 origin 138.658 E,35.4775 N; AEQD local metres x east,z south,y elevation-900',source:'GSI DEM resampled + PROCEDURAL lava relief and root mounds; procedural trees, not surveyed placements',centre:[camera.position.x,camera.position.z],sourceManifest:'provenance.json'};
 const gm=new THREE.MeshStandardMaterial({map:T.mossD,normalMap:T.mossN,roughnessMap:T.mossR,roughness:1});gm.name='Ground (moss base layer; runtime blends basalt/litter/trail)';g.add(new THREE.Mesh(groundPatch.geometry.clone(),gm));
 for(const o of forestGroup.children){if(!o.isInstancedMesh)continue;const matrix=new THREE.Matrix4();for(let i=0;i<o.count;i++){o.getMatrixAt(i,matrix);const p=new THREE.Vector3().setFromMatrixPosition(matrix);if(Math.abs(p.x-camera.position.x)>60||Math.abs(p.z-camera.position.z)>60)continue;const c=new THREE.Mesh(o.geometry,o.material);c.name=o.name.split(' ')[0];c.applyMatrix4(matrix);g.add(c);}}
 for(const o of decorGroup.children){if(o.isInstancedMesh){const matrix=new THREE.Matrix4();for(let i=0;i<o.count;i++){o.getMatrixAt(i,matrix);const c=new THREE.Mesh(o.geometry,o.material===groundMats.rock?new THREE.MeshStandardMaterial({map:T.rockD,normalMap:T.rockN,roughness:1}):o.material===logMat?new THREE.MeshStandardMaterial({map:logMat.userData.shader?.uniforms.tRockD.value,roughness:1}):o.material);c.name=o.name;c.applyMatrix4(matrix);g.add(c);}}else g.add(o.clone(true));}
 const exporter=new GLTFExporter();const ab=await exporter.parseAsync(g,{binary:true,onlyVisible:true,maxTextureSize:1024});const url=URL.createObjectURL(new Blob([ab],{type:'model/gltf-binary'}));const a=document.createElement('a');a.href=url;a.download=`Aokigahara_patch_E${Math.round(camera.position.x)}_S${Math.round(camera.position.z)}.glb`;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);toast('GLB exported. Preserve the source manifest with your model.');}catch(e){console.error(e);toast('This browser could not export the patch. Use the prepared corridor GLB instead.');}finally{btn.disabled=false;btn.textContent='Export current forest patch · GLB';}};
window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});
$('asset-credit').textContent='GSI elevation and aerial imagery; MOE vegetation; GSJ geology; © OpenStreetMap contributors (ODbL). Representative CC0 textures and fern, log and fir-spray/bark sources: Poly Haven. Trees, roots, lava relief, moss/litter distribution: procedural.';
// Inspection hook for headless audit renders (fixed cameras, identical before/after). No visual effect.
window.__aoki={get ready(){return ready},camera,scene,renderer,sample,groundY,get trees(){return trees},get small(){return small},PRESETS,
 setPose(x,z,yw,pt,eye=1.72){camera.position.set(x,0,z);if(Math.abs(x)<1000&&Math.abs(z)<1000&&Math.max(Math.abs(x-patchCX),Math.abs(z-patchCZ))>12)buildGroundPatch(x,z);camera.position.y=(groundY(x,z)??0)+eye;yaw=yw;pitch=pt;camera.rotation.set(pitch,yaw,0);entered=true;rebuildForest(true);},
 setPreset(p,angle){applyPreset(p,angle);},tick(){tick(.016);},render(){renderer.render(scene,camera);}};
init();
