import fs from 'node:fs';
import assert from 'node:assert/strict';
import {GLTFLoader} from './dist/vendor/addons/loaders/GLTFLoader.js';
globalThis.self=globalThis;
function stripTextures(buf){const n=buf.readUInt32LE(12),g=JSON.parse(buf.subarray(20,20+n)),off=20+n,bin=buf.subarray(off+8,off+8+buf.readUInt32LE(off));g.materials=g.materials.map(m=>({name:m.name,pbrMetallicRoughness:{baseColorFactor:m.pbrMetallicRoughness?.baseColorFactor??[1,1,1,1],roughnessFactor:1,metallicFactor:0},doubleSided:m.doubleSided}));g.images=[];g.textures=[];const js=Buffer.from(JSON.stringify(g)),pad=(4-js.length%4)%4,j=Buffer.concat([js,Buffer.alloc(pad,32)]),h=Buffer.alloc(20);h.writeUInt32LE(0x46546c67,0);h.writeUInt32LE(2,4);h.writeUInt32LE(28+j.length+bin.length,8);h.writeUInt32LE(j.length,12);h.writeUInt32LE(0x4e4f534a,16);const bh=Buffer.alloc(8);bh.writeUInt32LE(bin.length);bh.writeUInt32LE(0x004e4942,4);const r=Buffer.concat([h,j,bh,bin]);return r.buffer.slice(r.byteOffset,r.byteOffset+r.byteLength);}
for(const name of ['tree-library.glb','Aokigahara_Surface_Terrain.glb']){const result=await new GLTFLoader().parseAsync(stripTextures(fs.readFileSync('dist/assets/'+name)),'');let meshes=0,local=0,trees={};result.scene.traverse(o=>{if(o.isMesh){meshes++;if(o.material.name?.includes('Local_Ground'))local++;const m=o.name.match(/tree_(\d)_(high|low)/);if(m)trees[`${m[1]}_${m[2]}`]=(trees[`${m[1]}_${m[2]}`]??0)+1;assert(o.geometry.attributes.position.count>0);}});if(name.includes('tree'))assert.equal(Object.keys(trees).length,8);else assert(local>0);console.log(name,{meshes,local,trees});}
const buf=fs.readFileSync('dist/assets/forest-instances.f32'),a=new Float32Array(buf.buffer,buf.byteOffset,buf.length/4);assert.equal(a.length,53999*6);let near=0;for(let i=0;i<a.length;i+=6){assert(a[i+5]>=0&&a[i+5]<4);if(Math.hypot(a[i]-32.14,a[i+2]+9.84)<52)near++;}console.log('Tree placement array valid; detailed starting view:',near,'trees');
import {computeBoundsTree,acceleratedRaycast} from './dist/vendor/mesh-bvh.module.js';
import * as THREE from 'three';
THREE.BufferGeometry.prototype.computeBoundsTree=computeBoundsTree;THREE.Mesh.prototype.raycast=acceleratedRaycast;
const surface=(await new GLTFLoader().parseAsync(stripTextures(fs.readFileSync('dist/assets/Aokigahara_Surface_Terrain.glb')),'')).scene;surface.traverse(o=>{if(o.isMesh)o.geometry.computeBoundsTree();});surface.updateMatrixWorld(true);const ray=new THREE.Raycaster();ray.firstHitOnly=true;ray.ray.direction.set(0,-1,0);for(const [x,z]of [[32.14,-9.84],[-45,0],[775,300],[6307,12967]]){ray.ray.origin.set(x,10000,z);const h=ray.intersectObject(surface,true)[0];assert(h);assert(Number.isFinite(h.point.y));console.log('Terrain ray sample',x,z,h.point.y+900,'m');}
